### ISSUE TITLE
Consider packaging mesa-amber

### ISSUE THREAD

**Issue by retronica** [kth5/archpower#47]
Many older powerpc devices will not be supported by the drivers available in plain mesa

From some very limited testing on an iBook G4:
- Once i was able to tame xorg enough to get the system bootable to GUI, i found it was using llvmpipe.
- Compiling mesa-amber from the ABS is possible but :
     - Obviously quite slow.
     - I ended up removing all but my specific needed driver (r200), as compiling for the lot brings in bunch of dependencies i dont need/want.
     - Compiled without LTO as it would presumably have probably taken millenia and all but locked up the laptop when I tried with it enabled.
     - glxgears looks 'funky', but did run (maybe im missing some endianess patches?). inxi reports direct rendering is working.

**Comment by kth5** [comment]
I've been thinking about it but I do not have any pre-r300 ATI system.

That `glxgears` is busted is known, it locks up the entire system at times even on r300 and ppc32 with Nvidia Gforce 2 MX. It seems a general issue that has affected `mesa-demos` with Mesa since at least the 21.x versions.

Regarding compiling on actual pmac32 hardware, I highly recommend getting at least a dual G5 if not something higher end to build on natively. For ArchPOWER packages are built using a `KVM` instance running `linux-ppc64` in big-endian via cross endian support on a POWER9. There's simply no way we'd get anything done on bare-metal ppc big-endian. :(

I'll have a look at the amber branch and package it to my best efforts but I cannot personally test it.

**Comment by kth5** [comment]
Package is in `[base]` now as mentioned. Due to no further activity closing this issue. Feel free to re-open as needed.
