### ISSUE TITLE
PPC32

### ISSUE THREAD

**Issue by mrbubzie12** [kth5/archpower#66]
Hey just noticed no iso for current release…for the PowerPC32 side. Has that port been dropped and your only focusing on 64/LE going forward? Thanks for all you do :)

**Comment by kth5** [comment]
No the port has not been dropped. There is just no need at the moment to
spin a new ISO.

**Comment by mrbubzie12** [comment]
Ahhh ok reason I was asking is because there are currently no working webrowsers anymore other then arcticfox…gnome web(epiphany) vimb and qute no longer function and qute isn’t even installable anymore alone with a majority of kde not being available/installable either..a majority of the kde applications don’t working including konsolse started noticing around September’s release so wasn’t sure if the port was being dropped

**Comment by kth5** [comment]
The reason for vimb etc not working is due to the split of architecture indepdent packages into the `any` repository. Those may depend on packages from `base` or `testing` and in this case with `qt5-webengine` aren't available for anything but `powerpc64le` due to it being not portable to big endian platforms (much like `firefox`).

I don't see the problem installing Plasma/KDE on `powerpc` though I would not recommend running it unless you have a `nouveau` compatible card. Radeon is basically broken completely and using `fbdev` seems to be the most stable option on `powerpc` at this time.

If you have any issues beyond this, please file a more specified issue and we'll be able to address them.
