### ISSUE TITLE
"You are unable to access archlinuxpower.org"

### ISSUE THREAD

**Issue by leoneii** [kth5/archpower#69]
The site and repo on archlinuxpower.org are blocked for some reason, "You are unable to access archlinuxpower.org"

**Comment by leoneii** [comment]
ip  176.241.193.xx, everything works through vpn

**Comment by kth5** [comment]
After careful consideration I blocked all traffic from the Russian Federation due to the continued attacks on our networks and DDoSing afterwards. In addition to that the policical situation with the war of agression against the nation of Ukraine this was a worth while step.

I am sorry this affects you as an individual but there will never be a blocking affecting VPNs. with non-Russian exit nodes.

**Comment by leoneii** [comment]
I am pretty sure that the people of Ukraine, like the aggressors from Russia, do not give a damn about the availability of arch for the powerPC platform)) It is better, like me, to make a small donat for the armed forces of Ukraine. Unfortunately, VPN does not provide sufficient speed and convenience for installing and using the system. Well- Debian so Debian)
