### ISSUE TITLE
LXDE/LXQT

### ISSUE THREAD

**Issue by bradylegend32** [kth5/archpower#75]
Would it be possible to package LXDE? It's extremely fast on old hardware and truly fantastic. It might be a good option for legacy machines. I was averaging around 92MB of RAM usage on Debian, and it has a small footprint. Oh, and I was going to ask, is ATI still broken? I'm going to test KDE6 tonight! Thank you for all your help!

**Comment by kth5** [comment]
I wish I could tell you that ATI was fixed but I doubt it'll ever be to an extend you'd get full desktop accelleration for all cases. It works as is at this time. Plasma 6 works on supported platforms but on 32bit big endian there is still breakage that has nothing to do with GPU accelleration unfortunately. Defaults are patched for Arch POWER `powerpc` to disable GPU accelleration entirely to make Plasma applications without graphical glitches due to driver bugs.

I might have a look at LXDE but if it's a monster like Xfce4 (works fine on `powerpc` without quirks btw) or Plasma, I may decide not to package it since I do not use it myself. Stay tuned for now.

**Comment by kth5** [comment]
Both `lxde` and `lxqt` in `[testing]` now.
